# Generated by Django 3.2.8 on 2021-11-01 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_evacuated', models.DateTimeField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuating_barangay', to='relief.barangayprofile')),
                ('evacuation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_center', to='relief.evacuationcenter')),
            ],
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='barangays',
            field=models.ManyToManyField(related_name='barangays_evacuation', through='relief.EvacuationDetails', to='relief.BarangayProfile'),
        ),
    ]
