# Generated by Django 3.2.10 on 2022-11-19 05:09

from django.db import migrations, models
import relief.models


class Migration(migrations.Migration):

    dependencies = [
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'supplies'},
        ),
        migrations.AddField(
            model_name='supply',
            name='expiration_date',
            field=models.DateTimeField(default=relief.models.default_expiration_date, null=True, validators=[relief.models.future_date_validation], verbose_name='Expiration Date'),
        ),
    ]
